spring.application.name=gestion_ventas

#Configuracion de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gestion_ventas
spring.datasource.username=root
spring.datasource.password=Mg0730021-


#Cofiguraci?n de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

//Marca los errores en formato json

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false